---
- name: httpd is installed
  package:
    name: "{{ apache.package }}"
    state: installed

- name: httpd main config
  notify: reload apache
  template:
    src: httpd.conf.j2
    dest: "{{ apache.etc }}/conf/httpd.conf"
    backup: true

- name: directory for vhost config
  file:
    path: "{{ apache.etc }}/conf.vhosts.d"
    state: directory

- name: apache is running
  service:
    name: "{{ apache.service }}"
    state: started
    enabled: true

- name: vhosts.conf
  template:
    src: vhosts.conf
    dest: "{{ apache.etc }}/conf.d/vhosts.conf"
  notify: reload apache
