---
- name: httpd is installed
  package:
    name: "{{ apache.package }}"
    state: installed

- name: storage is managed, i.e. lvm, filesystems
  include_role:
    name: apache
    tasks_from: storage
  when: manage_storage

- name: symlink in /etc
  file:
    src: /opt/rh/httpd24/root/etc/httpd
    dest: /etc/opt/httpd24
    state: link

- name: directory for vhost config
  file:
    path: /opt/rh/httpd24/root/etc/httpd/conf.vhosts.d
    state: directory

- name: apache is running
  service:
    name: httpd24-httpd
    state: started
    enabled: true

- name: vhosts.conf
  template:
    src: vhosts.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/vhosts.conf
  notify: reload apache
