---

- name: logical volume for apache exists
  lvol:
    lv: www
    vg: lvm.{{inventory_hostname}}
    size: 1g

- name: create filesystem for apache
  filesystem:
    dev: /dev/lvm.{{inventory_hostname}}/www
    fstype: xfs

- name: mount point exists
  file:
    path: /var/www
    state: directory
    setype: httpd_sys_content_t

- name: mount apache partition
  mount:
    src: /dev/lvm.{{inventory_hostname}}/www
    path: /var/www
    state: mounted
    fstype: xfs
    opts: defaults,nodev,nosuid

- name: mount point exists
  file:
    path: /var/www
    state: directory
    setype: httpd_sys_content_t

- name: resize data filesystem for apache
  filesystem:
    dev: /dev/lvm.{{inventory_hostname}}/www
    fstype: xfs
    resizefs: yes
