---

- name: document root for {{ servername }}
  file:
    path: /var/www/{{ php_pool }}/{{ apache.documentroot }}
    state: directory
    owner: "{{ login }}"
    group: "{{ group }}"

- name: tmp dir for {{ servername }}
  file:
    path: /var/www/{{ php_pool }}/tmp
    state: directory
    mode: 01777
    setype: httpd_tmp_t

- name: special tmp directories for {{ servername }}
  file:
    path: /var/www/{{ php_pool }}/tmp/{{ item }}
    state: directory
    mode: 01777
    setype: httpd_tmp_t
  with_items:
    - session
    - wsdlcache
    - opcache

- name: put apache in users group
  user:
    name: apache
    groups: "{{ group }}"
    append: yes
  notify: reload apache

- name: virtual host {{ servername }} is configured
  template:
    src: "{{ item }}"
    dest: /opt/rh/httpd24/root/etc/httpd/conf.vhosts.d/{{ servername }}.conf
  with_first_found:
    - "{{ playbook_dir }}/templates/{{ vhost_cfg }}"  
    - vhost.conf.j2
  notify: reload apache
